# ===================================
#  Reorder Behavior Config
# ===================================

title: holgerbaumann.news::lang.button.reorder

nameFrom: name

modelClass: HolgerBaumann\News\Models\Categories

toolbar:
    buttons: reorder_toolbar
