# ===================================
#  Form Behavior Config
# ===================================

name: holgerbaumann.news::lang.title.categories
form: ~/plugins/holgerbaumann/news/models/categories/fields.yaml

modelClass: HolgerBaumann\News\Models\Categories
defaultRedirect: holgerbaumann/news/categories

create:
    redirect: holgerbaumann/news/categories/update/:id
    redirectClose: holgerbaumann/news/categories

update:
    redirect: holgerbaumann/news/categories/update/:id
    redirectClose: holgerbaumann/news/categories
