# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: holgerbaumann.news::lang.menu.import
    modelClass: HolgerBaumann\News\Models\PostsImport
    list: $/holgerbaumann/news/models/postsimport/columns.yaml
    redirect: holgerbaumann/news/posts
    permissions: holgerbaumann.news.import_export

export:
    title: holgerbaumann.news::lang.menu.export
    modelClass: HolgerBaumann\News\Models\PostsExport
    list: $/holgerbaumann/news/models/postsexport/columns.yaml
    redirect: holgerbaumann/news/posts
    permissions: holgerbaumann.news.import_export
    filename: posts.csv
