# ===================================
#  Form Behavior Config
# ===================================

name: holgerbaumann.news::lang.title.posts
form: ~/plugins/holgerbaumann/news/models/posts/fields.yaml

modelClass: HolgerBaumann\News\Models\Posts
defaultRedirect: holgerbaumann/news/posts

create:
    redirect: holgerbaumann/news/posts/update/:id
    redirectClose: holgerbaumann/news/posts

update:
    redirect: holgerbaumann/news/posts/update/:id
    redirectClose: holgerbaumann/news/posts
