# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: holgerbaumann.news::lang.menu.import
    modelClass: HolgerBaumann\News\Models\SubscribersImport
    list: $/holgerbaumann/news/models/subscribersimport/columns.yaml
    redirect: holgerbaumann/news/subscribers
    permissions: holgerbaumann.news.import_export

export:
    title: holgerbaumann.news::lang.menu.export
    modelClass: HolgerBaumann\News\Models\SubscribersExport
    list: $/holgerbaumann/news/models/subscribersexport/columns.yaml
    redirect: holgerbaumann/news/subscribers
    permissions: holgerbaumann.news.import_export
    filename: subscribers.csv
